[package]
name = "part2"
version = "0.1.0"
authors = ["Alejandro Rivero <nubcrack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.6"
num-traits = "0.2.11"